/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.pessoas;

import gui.enderecos.NovoEndereco;
import gui.modeltable.TableModelEndereco;
import gui.modeltable.TableModelPessoa;
import lib.dao.imp.endereco.endereco.EnderecoDao;
import lib.dao.imp.pessoa.PessoaDao;
import lib.model.endereco.Endereco;
import lib.model.pessoa.Pessoa;
import lib.model.pessoa.TipoPessoa;
import util.CpfCnpjValidator;
import util.MascaraMonetaria;

import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import java.awt.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author diego.lenz
 */
public class NovaPessoaForm extends javax.swing.JDialog {
    private Pessoa pessoa=new Pessoa();
    private PessoaDao pessoaDao;
    private List<Endereco> enderecos;
    private TipoPessoa tipoPessoa;
    private TableModelEndereco modeloend;
    private Endereco endereco;
  //  private List <Pessoa> listPCad= pessoaDao.listar();

    /**
     * Creates new form NovaPessoaForm
     */
    public NovaPessoaForm(javax.swing.JFrame parent, boolean modal) {
        super( parent, modal);
        initComponents();
    }

    public void bloqueiaedt() {
        this.txtConjuge.setEditable(false);
        this.txtCpf.setEditable(false);
        this.txtNome.setEditable(false);
        this.txtConjuge.setEditable(false);
        this.txtNomePai.setEditable(false);
        this.txtProfissao.setEditable(false);
        this.txtObservacoes.setEditable(false);
        this.txtRg.setEditable(false);
        this.txtSalario.setEditable(false);
        this.cmbSexo.setEditable(false);
        this.cmbEstadoCivil.setEditable(false);
    }

    public void carregapessoa() {
      //  pessoa = new Pessoa();
        pessoa.setNome(this.txtNome.getText());
        pessoa.setCpfCnpj(txtCpf.getText());
        pessoa.setDataNascimento(this.txtDtNasc.getDate());
        pessoa.setRgIe(txtRg.getText());
        pessoa.setLocalTrabalho(txtlocaltrab.getText());
        pessoa.setRazaoSocial(txtRazaoSocial.getText());
        pessoa.setProfissao(txtProfissao.getText());
        System.out.println(txtSalario.getText());
        if (txtSalario.getText()==""){
            txtSalario.setText("00.00");
        }
            pessoa.setValorSalario(Double.parseDouble(txtSalario.getText()));
        if (cmbtipocad.getSelectedItem() == "FISICA") {
            pessoa.setTipo(tipoPessoa.FISICA);
        } else if (cmbtipocad.getSelectedItem() == "JURIDICA") {
            pessoa.setTipo(tipoPessoa.JURIDICA);
        } else pessoa.setTipo(tipoPessoa.ESTRANGEIRO);


    }

    public void setpessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        pnlPrincipal2 = new javax.swing.JTabbedPane();
        pnlInformacoes2 = new javax.swing.JPanel();
        lblCpfCnpj = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtRg = new javax.swing.JTextField();
        lblRgIe = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        txtRazaoSocial = new javax.swing.JTextField();
        lblRazaoSocial = new javax.swing.JLabel();
        txtConjuge = new javax.swing.JTextField();
        txtNomeMae = new javax.swing.JTextField();
        txtNomePai = new javax.swing.JTextField();
        lblConjuge = new javax.swing.JLabel();
        lblNomeMae = new javax.swing.JLabel();
        lblNomePai = new javax.swing.JLabel();
        txtlocaltrab = new javax.swing.JTextField();
        txtProfissao = new javax.swing.JTextField();
        lblEmpresa = new javax.swing.JLabel();
        lblProfissao = new javax.swing.JLabel();
        lblObservacoes = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtObservacoes = new javax.swing.JTextArea();
        lblNome = new javax.swing.JLabel();
        lblSalario = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();
        lblEstadoCivil = new javax.swing.JLabel();
        cmbEstadoCivil = new javax.swing.JComboBox<>();
        lbltipocadstro = new javax.swing.JLabel();
        cmbtipocad = new javax.swing.JComboBox<>();
        lblDataNasc = new javax.swing.JLabel();
        txtSalario = new javax.swing.JFormattedTextField();
        txtDtNasc = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnenderecos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaend = new javax.swing.JTable();
        btnsalvar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nova pessoa");
        setBackground(new java.awt.Color(255, 255, 255));
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);

        pnlPrincipal2.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal2.setToolTipText("");
        pnlPrincipal2.setName(""); // NOI18N

        pnlInformacoes2.setBackground(new java.awt.Color(255, 255, 255));

        lblCpfCnpj.setText("CPF");

        lblRgIe.setText("RG");

        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });

        txtRazaoSocial.setEnabled(false);

        lblRazaoSocial.setText("Razao social");
        lblRazaoSocial.setEnabled(false);

        txtConjuge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConjugeActionPerformed(evt);
            }
        });

        lblConjuge.setText("Conjuge");

        lblNomeMae.setText("Nome da mae");

        lblNomePai.setText("Nome do pai");

        txtProfissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfissaoActionPerformed(evt);
            }
        });

        lblEmpresa.setText("Local de trabalho");

        lblProfissao.setText("Profissao");

        lblObservacoes.setText("Observacoes adicionais");

        txtObservacoes.setColumns(20);
        txtObservacoes.setRows(5);
        jScrollPane4.setViewportView(txtObservacoes);

        lblNome.setText("Nome completo");

        lblSalario.setText("Salario");

        lblSexo.setText("Sexo");

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        lblEstadoCivil.setText("Estado civil");

        cmbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viuvo(a)", "Separado(a)" }));

        lbltipocadstro.setText("tipo cadastro");

        cmbtipocad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FISICA", "JURIDICA", "ESTRANGEIRO" }));
        cmbtipocad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtipocadActionPerformed(evt);
            }
        });

        lblDataNasc.setText("Data de nascimento");

        txtSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0,00"))));
        txtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInformacoes2Layout = new javax.swing.GroupLayout(pnlInformacoes2);
        pnlInformacoes2.setLayout(pnlInformacoes2Layout);
        pnlInformacoes2Layout.setHorizontalGroup(
            pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacoes2Layout.createSequentialGroup()
                .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacoes2Layout.createSequentialGroup()
                        .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInformacoes2Layout.createSequentialGroup()
                                    .addComponent(lbltipocadstro)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbtipocad, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlInformacoes2Layout.createSequentialGroup()
                                    .addComponent(lblConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtConjuge))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnlInformacoes2Layout.createSequentialGroup()
                                            .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(pnlInformacoes2Layout.createSequentialGroup()
                                                        .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(lblCpfCnpj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(lblRgIe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(lblRazaoSocial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)))
                                                        .addGap(42, 42, 42))
                                                    .addComponent(lblNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblDataNasc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtCpf, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                                    .addComponent(txtRg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                                                .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cmbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(lblProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInformacoes2Layout.createSequentialGroup()
                                    .addComponent(lblNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlInformacoes2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtlocaltrab, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlInformacoes2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblObservacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(543, 543, 543))
            .addGroup(pnlInformacoes2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInformacoes2Layout.setVerticalGroup(
            pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacoes2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltipocadstro, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbtipocad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRgIe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEstadoCivil)
                    .addComponent(cmbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlocaltrab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInformacoes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacoes2Layout.createSequentialGroup()
                        .addComponent(txtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInformacoes2Layout.createSequentialGroup()
                        .addComponent(lblProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlPrincipal2.addTab("Informacoes basicas", pnlInformacoes2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("adicionar endereco");

        btnenderecos.setText("adicionar");
        btnenderecos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenderecosActionPerformed(evt);
            }
        });

        jButton1.setText("remover");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabelaend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabelaend);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnenderecos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 571, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 598, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnenderecos))
                .addGap(13, 13, 13))
        );

        pnlPrincipal2.addTab("enderecos", jPanel1);

        btnsalvar.setText("adicionar");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnsalvarActionPerformed(evt);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });

        btncancelar.setText("cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(566, Short.MAX_VALUE)
                .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancelar)
                    .addComponent(btnsalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDtNascPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtDtNascPropertyChange
        try {
            if (txtDtNasc.getDate().compareTo(new Date()) >= 0) {
                JOptionPane.showMessageDialog(this, "a data deve ser igual ou menor ao dia atual");
                txtDtNasc.setDate(null);
                txtDtNasc.requestFocus();
            }
        } catch (NullPointerException ex) {
            //            System.out.println("Alguma data ainda n�o foi informada. OK, prosseguir...");
        }
    }//GEN-LAST:event_txtDtNascPropertyChange

    private void tblEnderecosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEnderecosMouseClicked

    }//GEN-LAST:event_tblEnderecosMouseClicked

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnsalvarActionPerformed
        this.carregapessoa();

        if (pessoa.getCpfCnpj() == null || pessoa.getCpfCnpj().equals("")) {
            pessoa.setCpfCnpj(null);
        }
        if (pessoa.getNome() == null || pessoa.getNome().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "campo nome precisa ser preenchido");
            return;
        } else if (pessoa.getCpfCnpj() == null || pessoa.getCpfCnpj().equals("") && (pessoa.getTipo() != TipoPessoa.JURIDICA)) {
            JOptionPane.showMessageDialog(this, "campo cpf/cnpj precisa ser preenchido");
            return;
        } else if (pessoa.getCpfCnpj() != null) {
            pessoaDao = new PessoaDao();
            if (pessoaDao.getByCpfCnpjExato(pessoa.getCpfCnpj()).size() != 0) {
                JOptionPane.showMessageDialog(this, "campo cpf/cnpj ja cadastrado");
                return;
            }
            if (pessoa.getTipo().equals(TipoPessoa.JURIDICA)) {
                if (!CpfCnpjValidator.isCnpjValido(pessoa.getCpfCnpj())) {
                    JOptionPane.showMessageDialog(this, "O CNPJ informado não é válido");
                    return;
                }
            }


            else if (pessoa.getTipo().equals(TipoPessoa.FISICA)) {
                if (!CpfCnpjValidator.isCpfValido(pessoa.getCpfCnpj())) {

                    JOptionPane.showMessageDialog(this, "O Cpf informado não é válido");
                    return;
                }
            }


        } else if (pessoa.getDataNascimento() != null && pessoa.getDataNascimento().after(new Date())) {
            JOptionPane.showMessageDialog(
                    this,
                    "A data de nascimento não pode ser maior que a data atual"
            );
            return;
        }

        pessoa.setEnderecos(enderecos);
        EnderecoDao enderecoDao=new EnderecoDao();
        Endereco end=new Endereco();
        for ( int i=0; i< enderecos.size(); ) {
            enderecoDao.Inserir(enderecos.get(i));
            i=i+1;
        }
        try {
            pessoaDao = new PessoaDao();
            pessoaDao.Inserir(pessoa);
            JOptionPane.showMessageDialog(this, "salvo com sucesso");
            dispose();
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, "falha ao salvar");
        }
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnenderecosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenderecosActionPerformed
        // TODO add your handling code here:
        this.endereco=new Endereco();
        enderecos=new ArrayList<>();
        NovoEndereco.Callback callback = (endereco) -> {

            this.endereco=endereco;
           // this.endereco.setPessoas(pessoa);
            enderecos.add(this.endereco);
            modeloend =new TableModelEndereco();
            modeloend.setList(enderecos.toArray());
            this.tabelaend.setModel(modeloend);
        };
        NovoEndereco novoEndereco = new NovoEndereco(this, true, callback);
        novoEndereco.setVisible(true);
    }//GEN-LAST:event_btnenderecosActionPerformed

    private void cmbtipocadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtipocadActionPerformed
        // TODO add your handling code here:
        if (cmbtipocad.getSelectedItem() == "FISICA") {
            txtRazaoSocial.enable(false);
            lblCpfCnpj.setText("CPF");
            lblRgIe.setText("RG");
            txtDtNasc.enable(true);
            txtNome.enable(true);
        } else if (cmbtipocad.getSelectedItem() == "ESTRANGEIRO") {
            txtRazaoSocial.enable(false);
            lblRgIe.setText("documento");
            txtDtNasc.enable(true);
            txtNome.enable(true);
        } else {
            txtRazaoSocial.enable(true);
            txtNome.enable(false);
            lblCpfCnpj.setText("CNPJ");
            lblRgIe.setText("IE");
            txtDtNasc.enable(true);
            //txtNome.enable(true);
        }

    }//GEN-LAST:event_cmbtipocadActionPerformed

    private void txtConjugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConjugeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConjugeActionPerformed

    private void txtProfissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfissaoActionPerformed

    private void txtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioActionPerformed
        // TODO add your handling code here:
      //  MascaraMonetaria mascaraMonetaria=new MascaraMonetaria();
       // mascaraMonetaria.NumerosDecimais(10);
        //this.txtSalario.setDocument(mascaraMonetaria);
    }//GEN-LAST:event_txtSalarioActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaPessoaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaPessoaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaPessoaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaPessoaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NovaPessoaForm dialog = new NovaPessoaForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnenderecos;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JComboBox<String> cmbEstadoCivil;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JComboBox<String> cmbtipocad;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblConjuge;
    private javax.swing.JLabel lblCpfCnpj;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeMae;
    private javax.swing.JLabel lblNomePai;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblProfissao;
    private javax.swing.JLabel lblRazaoSocial;
    private javax.swing.JLabel lblRgIe;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lbltipocadstro;
    private javax.swing.JPanel pnlInformacoes2;
    private javax.swing.JTabbedPane pnlPrincipal2;
    private javax.swing.JTable tabelaend;
    private javax.swing.JTextField txtConjuge;
    private javax.swing.JFormattedTextField txtCpf;
    private com.toedter.calendar.JDateChooser txtDtNasc;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeMae;
    private javax.swing.JTextField txtNomePai;
    private javax.swing.JTextArea txtObservacoes;
    private javax.swing.JTextField txtProfissao;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JTextField txtRg;
    private javax.swing.JFormattedTextField txtSalario;
    private javax.swing.JTextField txtlocaltrab;
    // End of variables declaration//GEN-END:variables

}
