/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.selecionacota;

/**
 *
 * @author diego.lenz
 */
import gui.modeltable.TableModelApartamento;
import gui.modeltable.TableModelBloco;
import gui.modeltable.TableModelCota;
import gui.modeltable.TableModelPessoa;
import gui.pesquisa.Pesquisa;
import lib.dao.imp.apartamento.ApartamentoDao;
import lib.dao.imp.bloco.BlocoDao;
import lib.dao.imp.cotas.CotasDao;
import lib.dao.imp.hotel.HotelDao;
import lib.model.apartamento.Apartamento;
import lib.model.bloco.Bloco;
import lib.model.cotas.Cota;
import lib.model.hotel.Hotel;
import lib.model.pessoa.Pessoa;

import javax.swing.*;
import java.util.List;
public class SelecionaCota extends javax.swing.JDialog {

    /**
     * Creates new form NovoJDialog
     */
    private Hotel hotelselecionado=new Hotel();
    private Apartamento apartamentoselecionado=new Apartamento();
    private Bloco blocoselecionado=new Bloco();
    private Cota cotaselecionada=new Cota();
    private  ApartamentoDao apartamentodao=new ApartamentoDao();
    private  BlocoDao blocodao=new BlocoDao();
    private  HotelDao hoteldao=new HotelDao();
    private  CotasDao cotadao=new CotasDao();
    private  Callback callback;

    public void bloqueiaabas(){
        tabelaHotel.setEnabledAt(0,false);
        tabelaHotel.setEnabledAt(1,false);
        tabelaHotel.setEnabledAt(2, false);
        tabelaHotel.setEnabledAt(3,false);
    }

    public interface Callback {

        void handle(Apartamento apartamento);
    }


    public SelecionaCota(SelecionaCota.Callback callBack,java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bloqueiaabas();
        this.callback=callBack;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabelaHotel = new javax.swing.JTabbedPane();
        pnlhotel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edtdescricaocotas = new javax.swing.JTextField();
        brnpesquisarhtl = new javax.swing.JButton();
        cmbseleciona = new javax.swing.JComboBox<>();
        btnproseguirhotel = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelahotel = new javax.swing.JTable();
        pnlbloco = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelabloco = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cmbselecionabloco = new javax.swing.JComboBox<>();
        edtdescricaobloco = new javax.swing.JTextField();
        brnpesquisarbloco = new javax.swing.JButton();
        btnselecionarbloco = new javax.swing.JButton();
        btnvoltarbloco = new javax.swing.JButton();
        pnlapartamento = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbselecionaapartamento = new javax.swing.JComboBox<>();
        edtdescricaoapartamento = new javax.swing.JTextField();
        brnpesquisarapartamento = new javax.swing.JButton();
        btnvoltarapartamento = new javax.swing.JButton();
        btnselecionarapartamento = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaapartamento = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("selecao");

        tabelaHotel.setBackground(new java.awt.Color(255, 255, 255));
        tabelaHotel.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabelaHotel.setFocusCycleRoot(true);
        tabelaHotel.setFocusTraversalPolicyProvider(true);

        pnlhotel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Selecine o hotel");

        brnpesquisarhtl.setText("pesquisar");
        brnpesquisarhtl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnpesquisarhtlActionPerformed(evt);
            }
        });

        cmbseleciona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "descricao" }));
        cmbseleciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbselecionaActionPerformed(evt);
            }
        });

        btnproseguirhotel.setText("selecionar");
        btnproseguirhotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproseguirhotelActionPerformed(evt);
            }
        });

        tabelahotel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelahotel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelahotelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelahotel);

        javax.swing.GroupLayout pnlhotelLayout = new javax.swing.GroupLayout(pnlhotel);
        pnlhotel.setLayout(pnlhotelLayout);
        pnlhotelLayout.setHorizontalGroup(
            pnlhotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlhotelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlhotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlhotelLayout.createSequentialGroup()
                        .addComponent(cmbseleciona, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtdescricaocotas, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(brnpesquisarhtl, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlhotelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnproseguirhotel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlhotelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        pnlhotelLayout.setVerticalGroup(
            pnlhotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlhotelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlhotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlhotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(edtdescricaocotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(brnpesquisarhtl))
                    .addComponent(cmbseleciona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnproseguirhotel)
                .addGap(24, 24, 24))
        );

        tabelaHotel.addTab("Hotel", pnlhotel);

        pnlbloco.setBackground(new java.awt.Color(255, 255, 255));
        pnlbloco.setName("Bloco"); // NOI18N

        tabelabloco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabelabloco);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Selecine o bloco");

        cmbselecionabloco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por hotel" }));

        brnpesquisarbloco.setText("pesquisar");
        brnpesquisarbloco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnpesquisarblocoActionPerformed(evt);
            }
        });

        btnselecionarbloco.setText("selecionar");
        btnselecionarbloco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselecionarblocoActionPerformed(evt);
            }
        });

        btnvoltarbloco.setText("Voltar");
        btnvoltarbloco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarblocoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlblocoLayout = new javax.swing.GroupLayout(pnlbloco);
        pnlbloco.setLayout(pnlblocoLayout);
        pnlblocoLayout.setHorizontalGroup(
            pnlblocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlblocoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlblocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlblocoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnvoltarbloco, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnselecionarbloco, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlblocoLayout.createSequentialGroup()
                        .addComponent(cmbselecionabloco, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtdescricaobloco, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(brnpesquisarbloco, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlblocoLayout.setVerticalGroup(
            pnlblocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlblocoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlblocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbselecionabloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtdescricaobloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brnpesquisarbloco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlblocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnselecionarbloco)
                    .addComponent(btnvoltarbloco))
                .addGap(27, 27, 27))
        );

        tabelaHotel.addTab("Bloco", pnlbloco);

        pnlapartamento.setBackground(new java.awt.Color(255, 255, 255));
        pnlapartamento.setName("Apartamento"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Selecine o apartamento");

        cmbselecionaapartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por bloco" }));

        brnpesquisarapartamento.setText("pesquisar");
        brnpesquisarapartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnpesquisarapartamentoActionPerformed(evt);
            }
        });

        btnvoltarapartamento.setText("Voltar");
        btnvoltarapartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarapartamentoActionPerformed(evt);
            }
        });

        btnselecionarapartamento.setText("selecionar");
        btnselecionarapartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselecionarapartamentoActionPerformed(evt);
            }
        });

        tabelaapartamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tabelaapartamento);

        javax.swing.GroupLayout pnlapartamentoLayout = new javax.swing.GroupLayout(pnlapartamento);
        pnlapartamento.setLayout(pnlapartamentoLayout);
        pnlapartamentoLayout.setHorizontalGroup(
            pnlapartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlapartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlapartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlapartamentoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnvoltarapartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnselecionarapartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlapartamentoLayout.createSequentialGroup()
                        .addGroup(pnlapartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlapartamentoLayout.createSequentialGroup()
                                .addComponent(cmbselecionaapartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtdescricaoapartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(brnpesquisarapartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlapartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlapartamentoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3)
                    .addContainerGap()))
        );
        pnlapartamentoLayout.setVerticalGroup(
            pnlapartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlapartamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlapartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbselecionaapartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtdescricaoapartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brnpesquisarapartamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 354, Short.MAX_VALUE)
                .addGroup(pnlapartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnvoltarapartamento)
                    .addComponent(btnselecionarapartamento))
                .addGap(24, 24, 24))
            .addGroup(pnlapartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlapartamentoLayout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(76, Short.MAX_VALUE)))
        );

        tabelaHotel.addTab("Apartamento", pnlapartamento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelaHotel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelaHotel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void brnpesquisarhtlActionPerformed(java.awt.event.ActionEvent evt) {
        TableModelPessoa modelo=new TableModelPessoa();
        List listhotel =hoteldao.listar();
        this.tabelahotel.setModel(modelo);
        modelo.setList(listhotel.toArray());
    }

    private void btnproseguirhotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproseguirhotelActionPerformed
        // TODO add your handling code here:
        if (this.tabelahotel.getSelectedRow() >= 0) {
            Integer id = (Integer) this.tabelahotel.getValueAt(this.tabelahotel.getSelectedRow(), 0);
            hotelselecionado= (Hotel) hoteldao.carregar(id);
            edtdescricaobloco.setText(hotelselecionado.getNome());
            this.tabelaHotel.setSelectedIndex(1);

        } else JOptionPane.showMessageDialog(this, "Selecione um hotel para prosseguir");
    }//GEN-LAST:event_btnproseguirhotelActionPerformed

    private void brnpesquisarblocoActionPerformed(java.awt.event.ActionEvent evt) {
        TableModelBloco modelo=new TableModelBloco();
        List listbloco = hotelselecionado.getBlocos();
        this.tabelabloco.setModel(modelo);
        modelo.setList(listbloco.toArray());
    }

    private void btnselecionarblocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselecionarblocoActionPerformed
        if (this.tabelabloco.getSelectedRow() >= 0) {
            Integer id = (Integer) this.tabelabloco.getValueAt(this.tabelabloco.getSelectedRow(), 0);
            blocoselecionado= (Bloco) blocodao.carregar(id);
            edtdescricaoapartamento.setText(blocoselecionado.getDescricao());
            this.tabelaHotel.setSelectedIndex(2);

        } else JOptionPane.showMessageDialog(this, "Selecione um bloco para prosseguir");
    }//GEN-LAST:event_btnselecionarblocoActionPerformed

    private void btnvoltarblocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarblocoActionPerformed
        this.tabelaHotel.setSelectedIndex(0);

    }//GEN-LAST:event_btnvoltarblocoActionPerformed

    private void brnpesquisarapartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnpesquisarapartamentoActionPerformed
        // TODO add your handling code here:
        TableModelApartamento modelo=new TableModelApartamento();
        List list = apartamentodao.listarporbloco(blocoselecionado);
        this.tabelaapartamento.setModel(modelo);
        modelo.setList(list.toArray());
    }//GEN-LAST:event_brnpesquisarapartamentoActionPerformed

    private void btnvoltarapartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarapartamentoActionPerformed
        // TODO add your handling code here:
        this.tabelaHotel.setSelectedIndex(1);
    }//GEN-LAST:event_btnvoltarapartamentoActionPerformed

    private void btnselecionarapartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselecionarapartamentoActionPerformed
        if (this.tabelaapartamento.getSelectedRow() >= 0) {
            Integer id = (Integer) this.tabelaapartamento.getValueAt(this.tabelaapartamento.getSelectedRow(), 0);
            apartamentoselecionado = (Apartamento) apartamentodao.carregar(id);
            edtdescricaocotas.setText(String.valueOf(apartamentoselecionado.getNumero()));
            this.tabelaHotel.setSelectedIndex(3);


        } else JOptionPane.showMessageDialog(this, "Selecione um apartamento para prosseguir");
    }//GEN-LAST:event_btnselecionarapartamentoActionPerformed

    private void tabelahotelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelahotelMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tabelahotelMouseClicked

    private void cmbselecionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbselecionaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbselecionaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecionaCota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecionaCota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecionaCota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecionaCota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelecionaCota dialog = new SelecionaCota(null,new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnpesquisarapartamento;
    private javax.swing.JButton brnpesquisarbloco;
    private javax.swing.JButton brnpesquisarhtl;
    private javax.swing.JToggleButton btnproseguirhotel;
    private javax.swing.JButton btnselecionarapartamento;
    private javax.swing.JButton btnselecionarbloco;
    private javax.swing.JButton btnvoltarapartamento;
    private javax.swing.JButton btnvoltarbloco;
    private javax.swing.JComboBox<String> cmbseleciona;
    private javax.swing.JComboBox<String> cmbselecionaapartamento;
    private javax.swing.JComboBox<String> cmbselecionabloco;
    private javax.swing.JTextField edtdescricaoapartamento;
    private javax.swing.JTextField edtdescricaobloco;
    private javax.swing.JTextField edtdescricaocotas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnlapartamento;
    private javax.swing.JPanel pnlbloco;
    private javax.swing.JPanel pnlhotel;
    private javax.swing.JTabbedPane tabelaHotel;
    private javax.swing.JTable tabelaapartamento;
    private javax.swing.JTable tabelabloco;
    private javax.swing.JTable tabelahotel;
    // End of variables declaration//GEN-END:variables
}
