/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.cotas.ConsultarCotas;
import gui.cotas.Vendercota;
import gui.cotas.modelocotas.ConsultaModeloCota;
import gui.hotel.ConsultaHoteis;
import gui.pessoas.ConsultarPessoa;
import gui.pessoas.ConsultarPessoas;
import gui.pessoas.NovaPessoaForm;
import lib.dao.AbstractDao;

/**
 *
 * @author diego.lenz
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        AbstractDao.estanciaem();
        setExtendedState(MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmnuconsultacota = new javax.swing.JMenuItem();
        mnuitmmodelocotas = new javax.swing.JMenuItem();
        jmnuvendercota = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmnucadpessoa = new javax.swing.JMenuItem();
        mnuhotel = new javax.swing.JMenu();
        submnuconshotel = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 897, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        jMenu1.setText("cota");

        jmnuconsultacota.setText("consultar cota");
        jmnuconsultacota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuconsultacotaActionPerformed(evt);
            }
        });
        jMenu1.add(jmnuconsultacota);

        mnuitmmodelocotas.setText("consultar modelos de cotas");
        mnuitmmodelocotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitmmodelocotasActionPerformed(evt);
            }
        });
        jMenu1.add(mnuitmmodelocotas);

        jmnuvendercota.setText("vender cota");
        jmnuvendercota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuvendercotaActionPerformed(evt);
            }
        });
        jMenu1.add(jmnuvendercota);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("pessoas");

        jMenuItem1.setText("consultar pessoas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jmnucadpessoa.setText("cadastrar pessoas");
        jmnucadpessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnucadpessoaActionPerformed(evt);
            }
        });
        jMenu2.add(jmnucadpessoa);

        jMenuBar1.add(jMenu2);

        mnuhotel.setText("hoteis");

        submnuconshotel.setText("consultar hotel");
        submnuconshotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submnuconshotelActionPerformed(evt);
            }
        });
        mnuhotel.add(submnuconshotel);

        jMenuBar1.add(mnuhotel);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmnucadpessoaActionPerformed(java.awt.event.ActionEvent evt) {                                              
     


    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ConsultarPessoa obj=new ConsultarPessoa();
        obj.setVisible(true);
        obj.setSize(this.jDesktopPane1.getSize());
        this.jDesktopPane1.add(obj);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmnuconsultacotaActionPerformed(java.awt.event.ActionEvent evt) {
        ConsultarCotas consultarCotas=new ConsultarCotas();
        consultarCotas.setVisible(true);
        consultarCotas.setSize(this.jDesktopPane1.getSize());
        consultarCotas.setaframe(this); //metodo para setar o jframe principal pra abrir os j dialog dentro do mesmo
        this.jDesktopPane1.add(consultarCotas);
    }

    private void jmnuvendercotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuvendercotaActionPerformed
        // TODO add your handling code here:
        Vendercota obj=new Vendercota();
        obj.setVisible(true);
        obj.setSize(this.jDesktopPane1.getSize());
        obj.setaframe(this); //metodo para setar o jframe principal pra abrir os j dialog dentro do mesmo
        this.jDesktopPane1.add(obj);
        //NovaPessoaForm novaPessoaForm=new NovaPessoaForm(this, true);
        //novaPessoaForm.setVisible(true);

    }//GEN-LAST:event_jmnuvendercotaActionPerformed

    private void submnuconshotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submnuconshotelActionPerformed
        // TODO add your handling code here:
        ConsultaHoteis obj =new ConsultaHoteis();
        obj.setVisible(true);
        obj.setSize(this.jDesktopPane1.getSize());
      //  obj.setaframe(this); //metodo para setar o jframe principal pra abrir os j dialog dentro do mesmo
        this.jDesktopPane1.add(obj);
    }//GEN-LAST:event_submnuconshotelActionPerformed

    private void mnuitmmodelocotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitmmodelocotasActionPerformed
        // TODO add your handling code here:
           ConsultaModeloCota obj=new ConsultaModeloCota();
        obj.setVisible(true);
        obj.setSize(this.jDesktopPane1.getSize());
        this.jDesktopPane1.add(obj);
    }//GEN-LAST:event_mnuitmmodelocotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jmnucadpessoa;
    private javax.swing.JMenuItem jmnuconsultacota;
    private javax.swing.JMenuItem jmnuvendercota;
    private javax.swing.JMenu mnuhotel;
    private javax.swing.JMenuItem mnuitmmodelocotas;
    private javax.swing.JMenuItem submnuconshotel;
    // End of variables declaration//GEN-END:variables
}
