/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.enderecos.bairro;

import javafx.collections.ObservableList;
import lib.dao.imp.endereco.bairro.BairroDao;
import lib.dao.imp.endereco.estado.EstadoDao;
import lib.model.endereco.bairro.Bairro;
import lib.model.endereco.cidade.Cidade;
import lib.model.endereco.estado.Estado;
import lib.model.endereco.pais.Pais;
import lib.model.endereco.provincia.Provincia;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ItemEvent;
import java.util.List;

/**
 *
 * @author diego.lenz
 */
public class NovoBairro extends javax.swing.JDialog {
    private  ObservableList<Estado> estados;
    private  ObservableList<Cidade> cidades;
    private  ObservableList<Provincia> provincias;
    private Estado estadoSelecionado;
    private Provincia provinciaSelecionado;
    private Pais paisSelecionado;
    private Cidade cidadeSelecionado;
    private  Bairro bairro;
    private  boolean modoAdicao;
    private boolean salvo;
    private Pais ultimoPais;
    /**
     * Creates new form NovoBairro
     */
    public NovoBairro(Window parent, boolean modal, Bairro  bairro) {
        super((Dialog) parent, modal);
        this.bairro=bairro;
        modoAdicao=bairro.getId() == null;
        initComponents();
    }

    public void setcidade(Cidade cidade){
        cidadeSelecionado=cidade;
        DefaultComboBoxModel comboBoxModel=new DefaultComboBoxModel();
       // comboBoxModel.addElement("selecione");
        DefaultComboBoxModel comboBoxModelest=new DefaultComboBoxModel();
        if (cidadeSelecionado.getEstado().getPais().toString().equalsIgnoreCase("brasil")) {
            comboBoxModel.addElement(Pais.BRASIL);

        } else if (cidadeSelecionado.getEstado().getPais().toString().equalsIgnoreCase("argentina")) {
            comboBoxModel.addElement(Pais.ARGENTINA);
            this.cmbEstado.setModel(comboBoxModelest);
        } else {
            comboBoxModel.addElement(Pais.PARAGUAI);
        }
        this.cmbPais.setModel(comboBoxModel);
        DefaultComboBoxModel comboBoxModelcid=new DefaultComboBoxModel();
        comboBoxModelcid.addElement(cidadeSelecionado);
        comboBoxModelest.addElement(cidadeSelecionado.getEstado());
        this.cmbEstado.setModel(comboBoxModelest);
        this.cmbCidade.setModel(comboBoxModelcid);
        this.cmbEstado.setEnabled(false);
        this.cmbCidade.setEnabled(false);
        this.cmbPais.setEnabled(false);
        this.cmbProvincia.setEnabled(false);



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        edtCep = new javax.swing.JFormattedTextField();
        cmbEstado = new javax.swing.JComboBox<>();
        cmbCidade = new javax.swing.JComboBox<>();
        cmbPais = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cmbProvincia = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setText("Novo bairro");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel2.setText("Nome");

        jLabel3.setText("CEP");

        jLabel4.setText("Estado");

        jLabel5.setText("Cidade");

        try {
            edtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cmbEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEstadoItemStateChanged(evt);
            }
        });

        cmbPais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPaisItemStateChanged(evt);
            }
        });

        jLabel1.setText("Pa�s");

        cmbProvincia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbProvinciaItemStateChanged(evt);
            }
        });

        jLabel6.setText("Prov�ncia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbProvincia, 0, 178, Short.MAX_VALUE)
                            .addComponent(edtNome)
                            .addComponent(edtCep)
                            .addComponent(cmbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbCidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbPais, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getRootPane().setDefaultButton(btnCancelar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        this.bairro.setNome(edtNome.getText());
        this.bairro.setCidade((Cidade) cmbCidade.getSelectedItem());
        this.bairro.setCep(edtCep.getText());

        if (bairro.getNome() == null || bairro.getNome().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum nome informado, Informe um nome para o bairro");
            return;
        }

        if (bairro.getCep() == null || bairro.getCep().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum CEP informado, Informe um CEP para o bairro");
            return;
        }

        if (cmbCidade.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Nenhum cidade informado, Informe uma cidade para prosseguir");
            return;
        }
        /*
        //fazer essa validacao futuramente
        Bairro bairroRetorno = new BairroDa().getByNomeCidade(bairro.getNome(), bairro.getCidade());
        if (bairroRetorno != null && !bairroRetorno.equals(bairro)) {
            DialogBuilderFactory.aviso("Nome duplicado", "O nome informado j� est� em uso por outro bairro na cidade selecionada").exibir();
            return;
        }*/

       // fazer uma implentcao futura de uma tela(jdialog) que carrega enquanto salva o obj PreloaderDialog.Proxy preloader = PreloaderDialog.newInstance(this, "Salvando bairro");
       // preloader.iniciar(() -> {
            try {
                if (modoAdicao) {
                    new BairroDao().Inserir(bairro);
                } else {
                    new BairroDao().Alterar(bairro);
                }
            } catch (Throwable e) {
               // preloader.ocultar();
                JOptionPane.showMessageDialog(this, "erro ao salvar objeto, verrifique as informações e tente novamente");;
                return;
            }
            this.salvo = true;
            //preloader.ocultar();
            JOptionPane.showMessageDialog(this, "Salvo com sucesso");;
            dispose();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        boolean cancelar;
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "CANCELAMENTO", JOptionPane.YES_OPTION,JOptionPane.NO_OPTION )==JOptionPane.NO_OPTION) {
            cancelar=true;
        }else cancelar=false;

        if (cancelar) {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEstadoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (this.cmbEstado.getSelectedIndex() > -1) {
                estadoSelecionado = (Estado) cmbEstado.getSelectedItem();
                cidades.clear();
                cidades.addAll(estadoSelecionado.getCidadeList());
            }
        }
    }//GEN-LAST:event_cmbEstadoItemStateChanged

    private void cmbPaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPaisItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            paisSelecionado = (Pais) cmbPais.getSelectedItem();
            if (paisSelecionado == ultimoPais) {
                return;
            }
            ultimoPais = paisSelecionado;

            edtCep.setValue(null);
            edtCep.setText(paisSelecionado.getZipCode());
            edtCep.repaint();

            estados.clear();
            cidades.clear();

            if (paisSelecionado.equals(Pais.ARGENTINA)) {
                cmbProvincia.setEnabled(true);

                if (!provincias.isEmpty()) {
                    if (!modoAdicao) {
                        cmbProvincia.setSelectedItem(provinciaSelecionado);
                    } else {
                        cmbProvincia.setSelectedIndex(0);
                    }
                }

            } else {
                estados.addAll(new EstadoDao().getByPais(paisSelecionado));
                cmbProvincia.setEnabled(false);
                cmbProvincia.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_cmbPaisItemStateChanged

    private void cmbProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbProvinciaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            provinciaSelecionado = (Provincia) cmbProvincia.getSelectedItem();
            estados.clear();
            cidades.clear();
            estados.addAll(provinciaSelecionado.getEstados());
        }
    }//GEN-LAST:event_cmbProvinciaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NovoBairro dialog = new NovoBairro(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public boolean isSalvo() {
        return salvo;
    }
    public Bairro getBairro() {
        return bairro;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbCidade;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbPais;
    private javax.swing.JComboBox<String> cmbProvincia;
    private javax.swing.JFormattedTextField edtCep;
    private javax.swing.JTextField edtNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
