INSERT INTO tb_estado (id, nome, sigla, codigo_ibge, pais, provincia) VALUES
  (21, 'Rond�nia', 'RO', 11, 'BRASIL', NULL),
  (1, 'Acre', 'AC', 12, 'BRASIL', NULL),
  (3, 'Amazonas', 'AM', 13, 'BRASIL', NULL),
  (22, 'Roraima', 'RR', 14, 'BRASIL', NULL),
  (14, 'Par�', 'PA', 15, 'BRASIL', NULL),
  (4, 'Amap�', 'AP', 16, 'BRASIL', NULL),
  (27, 'Tocantins', 'TO', 17, 'BRASIL', NULL),
  (10, 'Maranh�o', 'MA', 21, 'BRASIL', NULL),
  (17, 'Piau�', 'PI', 22, 'BRASIL', NULL),
  (6, 'Cear�', 'CE', 23, 'BRASIL', NULL),
  (20, 'Rio Grande do Norte', 'RN', 24, 'BRASIL', NULL),
  (15, 'Para�ba', 'PB', 25, 'BRASIL', NULL),
  (16, 'Pernambuco', 'PE', 26, 'BRASIL', NULL),
  (2, 'Alagoas', 'AL', 27, 'BRASIL', NULL),
  (25, 'Sergipe', 'SE', 28, 'BRASIL', NULL),
  (5, 'Bahia', 'BA', 29, 'BRASIL', NULL),
  (11, 'Minas Gerais', 'MG', 31, 'BRASIL', NULL),
  (8, 'Espirito Santo', 'ES', 32, 'BRASIL', NULL),
  (19, 'Rio de Janeiro', 'RJ', 33, 'BRASIL', NULL),
  (26, 'S�o Paulo', 'SP', 35, 'BRASIL', NULL),
  (18, 'Paran�', 'PR', 41, 'BRASIL', NULL),
  (24, 'Santa Catarina', 'SC', 42, 'BRASIL', NULL),
  (23, 'Rio Grande do Sul', 'RS', 43, 'BRASIL', NULL),
  (12, 'Mato Grosso do Sul', 'MS', 50, 'BRASIL', NULL),
  (13, 'Mato Grosso', 'MT', 51, 'BRASIL', NULL),
  (9, 'Goi�s', 'GO', 52, 'BRASIL', NULL),
  (7, 'Distrito Federal', 'DF', 53, 'BRASIL', NULL),
  (28, 'Teste edi��o', 'Te', 123, 'BRASIL', NULL),
  (29, 'Adolfo Alsina', NULL, NULL, 'ARGENTINA', 1),
  (30, 'Adolfo Gonzales Chaves', NULL, NULL, 'ARGENTINA', 1),
  (31, 'Alberti', NULL, NULL, 'ARGENTINA', 1),
  (32, 'Almirante Brown', NULL, NULL, 'ARGENTINA', 1),
  (33, 'Arrecifes', NULL, NULL, 'ARGENTINA', 1),
  (34, 'Avellaneda', NULL, NULL, 'ARGENTINA', 1),
  (35, 'Ayacucho', NULL, NULL, 'ARGENTINA', 1),
  (36, 'Azul', NULL, NULL, 'ARGENTINA', 1),
  (37, 'Bah�a Blanca', NULL, NULL, 'ARGENTINA', 1),
  (38, 'Balcarce', NULL, NULL, 'ARGENTINA', 1),
  (39, 'Baradero', NULL, NULL, 'ARGENTINA', 1),
  (40, 'Benito Ju�rez', NULL, NULL, 'ARGENTINA', 1),
  (41, 'Berazategui', NULL, NULL, 'ARGENTINA', 1),
  (42, 'Berisso', NULL, NULL, 'ARGENTINA', 1),
  (43, 'Bol�var', NULL, NULL, 'ARGENTINA', 1),
  (44, 'Bragado', NULL, NULL, 'ARGENTINA', 1),
  (45, 'Brandsen', NULL, NULL, 'ARGENTINA', 1),
  (46, 'Campana', NULL, NULL, 'ARGENTINA', 1),
  (47, 'Capit�n Sarmiento Carlos', NULL, NULL, 'ARGENTINA', 1),
  (48, 'Carlos Casares', NULL, NULL, 'ARGENTINA', 1),
  (49, 'Carlos Tejedor', NULL, NULL, 'ARGENTINA', 1),
  (50, 'Carmen de Areco', NULL, NULL, 'ARGENTINA', 1),
  (51, 'Castelli', NULL, NULL, 'ARGENTINA', 1),
  (52, 'Ca�uelas', NULL, NULL, 'ARGENTINA', 1),
  (53, 'Chacabuco', NULL, NULL, 'ARGENTINA', 1),
  (54, 'Chascom�s', NULL, NULL, 'ARGENTINA', 1),
  (55, 'Chivilcoy', NULL, NULL, 'ARGENTINA', 1),
  (56, 'Col�n', NULL, NULL, 'ARGENTINA', 1),
  (57, 'Coronel de Marina Leonardo Rosales', NULL, NULL, 'ARGENTINA', 1),
  (58, 'Coronel Dorrego', NULL, NULL, 'ARGENTINA', 1),
  (59, 'Coronel Pringles', NULL, NULL, 'ARGENTINA', 1),
  (60, 'Coronel Su�rez', NULL, NULL, 'ARGENTINA', 1),
  (61, 'Daireaux', NULL, NULL, 'ARGENTINA', 1),
  (62, 'Dolores', NULL, NULL, 'ARGENTINA', 1),
  (63, 'Ensenada', NULL, NULL, 'ARGENTINA', 1),
  (64, 'Escobar', NULL, NULL, 'ARGENTINA', 1),
  (65, 'Esteban Echeverr�a', NULL, NULL, 'ARGENTINA', 1),
  (66, 'Exaltaci�n de la Cruz', NULL, NULL, 'ARGENTINA', 1),
  (67, 'Ezeiza', NULL, NULL, 'ARGENTINA', 1),
  (68, 'Florencio Varela', NULL, NULL, 'ARGENTINA', 1),
  (69, 'Florentino Ameghino', NULL, NULL, 'ARGENTINA', 1),
  (70, 'General Alvarado', NULL, NULL, 'ARGENTINA', 1),
  (71, 'General Alvear', NULL, NULL, 'ARGENTINA', 1),
  (72, 'General Arenales', NULL, NULL, 'ARGENTINA', 1),
  (73, 'General Belgrano', NULL, NULL, 'ARGENTINA', 1),
  (74, 'General Guido', NULL, NULL, 'ARGENTINA', 1),
  (75, 'General Juan Madariaga', NULL, NULL, 'ARGENTINA', 1),
  (76, 'General La Madrid', NULL, NULL, 'ARGENTINA', 1),
  (77, 'General Las Heras', NULL, NULL, 'ARGENTINA', 1),
  (78, 'General Lavalle', NULL, NULL, 'ARGENTINA', 1),
  (79, 'General Paz', NULL, NULL, 'ARGENTINA', 1),
  (80, 'General Pinto', NULL, NULL, 'ARGENTINA', 1),
  (81, 'General Pueyrred�n', NULL, NULL, 'ARGENTINA', 1),
  (82, 'General Rodr�guez', NULL, NULL, 'ARGENTINA', 1),
  (83, 'General San Mart�n', NULL, NULL, 'ARGENTINA', 1),
  (84, 'General Viamonte', NULL, NULL, 'ARGENTINA', 1),
  (85, 'General Villegas', NULL, NULL, 'ARGENTINA', 1),
  (86, 'Guamin�', NULL, NULL, 'ARGENTINA', 1),
  (87, 'Hip�lito Yrigoyen', NULL, NULL, 'ARGENTINA', 1),
  (88, 'Hurlingham', NULL, NULL, 'ARGENTINA', 1),
  (89, 'Ituzaing�', NULL, NULL, 'ARGENTINA', 1),
  (90, 'Jos� C. Paz', NULL, NULL, 'ARGENTINA', 1),
  (91, 'Jun�n', NULL, NULL, 'ARGENTINA', 1),
  (92, 'La Costa', NULL, NULL, 'ARGENTINA', 1),
  (93, 'La Matanza', NULL, NULL, 'ARGENTINA', 1),
  (94, 'Lan�s', NULL, NULL, 'ARGENTINA', 1),
  (95, 'La Plata', NULL, NULL, 'ARGENTINA', 1),
  (96, 'Laprida', NULL, NULL, 'ARGENTINA', 1),
  (97, 'Las Flores', NULL, NULL, 'ARGENTINA', 1),
  (98, 'Leandro N. Alem', NULL, NULL, 'ARGENTINA', 1),
  (99, 'Lincoln', NULL, NULL, 'ARGENTINA', 1),
  (100, 'Lober�a', NULL, NULL, 'ARGENTINA', 1),
  (101, 'Lobos', NULL, NULL, 'ARGENTINA', 1),
  (102, 'Lomas de Zamora', NULL, NULL, 'ARGENTINA', 1),
  (103, 'Luj�n', NULL, NULL, 'ARGENTINA', 1),
  (104, 'Magdalena', NULL, NULL, 'ARGENTINA', 1),
  (105, 'Maip�', NULL, NULL, 'ARGENTINA', 1),
  (106, 'Malvinas Argentinas', NULL, NULL, 'ARGENTINA', 1),
  (107, 'Mar Chiquita', NULL, NULL, 'ARGENTINA', 1),
  (108, 'Marcos Paz', NULL, NULL, 'ARGENTINA', 1),
  (109, 'Mercedes', NULL, NULL, 'ARGENTINA', 1),
  (110, 'Merlo', NULL, NULL, 'ARGENTINA', 1),
  (111, 'Monte', NULL, NULL, 'ARGENTINA', 1),
  (112, 'Monte Hermoso', NULL, NULL, 'ARGENTINA', 1),
  (113, 'Moreno', NULL, NULL, 'ARGENTINA', 1),
  (114, 'Mor�n', NULL, NULL, 'ARGENTINA', 1),
  (115, 'Navarro', NULL, NULL, 'ARGENTINA', 1),
  (116, 'Necochea', NULL, NULL, 'ARGENTINA', 1),
  (117, 'Nueve de Julio', NULL, NULL, 'ARGENTINA', 1),
  (118, 'Olavarr�a', NULL, NULL, 'ARGENTINA', 1),
  (119, 'Patagones', NULL, NULL, 'ARGENTINA', 1),
  (120, 'Pehuaj�', NULL, NULL, 'ARGENTINA', 1),
  (121, 'Pellegrini', NULL, NULL, 'ARGENTINA', 1),
  (122, 'Pergamino', NULL, NULL, 'ARGENTINA', 1),
  (123, 'Pila', NULL, NULL, 'ARGENTINA', 1),
  (124, 'Pilar', NULL, NULL, 'ARGENTINA', 1),
  (125, 'Pinamar', NULL, NULL, 'ARGENTINA', 1),
  (126, 'Presidente Per�n', NULL, NULL, 'ARGENTINA', 1),
  (127, 'Puan', NULL, NULL, 'ARGENTINA', 1),
  (128, 'Punta Indio', NULL, NULL, 'ARGENTINA', 1),
  (129, 'Quilmes', NULL, NULL, 'ARGENTINA', 1),
  (130, 'Ramallo', NULL, NULL, 'ARGENTINA', 1),
  (131, 'Rauch', NULL, NULL, 'ARGENTINA', 1),
  (132, 'Rivadavia', NULL, NULL, 'ARGENTINA', 1),
  (133, 'Rojas', NULL, NULL, 'ARGENTINA', 1),
  (134, 'Roque P�rez', NULL, NULL, 'ARGENTINA', 1),
  (135, 'Saavedra', NULL, NULL, 'ARGENTINA', 1),
  (136, 'Saladillo', NULL, NULL, 'ARGENTINA', 1),
  (137, 'Salliquel�', NULL, NULL, 'ARGENTINA', 1),
  (138, 'Salto', NULL, NULL, 'ARGENTINA', 1),
  (139, 'San Andr�s de Giles', NULL, NULL, 'ARGENTINA', 1),
  (140, 'San Antonio de Areco', NULL, NULL, 'ARGENTINA', 1),
  (141, 'San Cayetano', NULL, NULL, 'ARGENTINA', 1),
  (142, 'San Fernando', NULL, NULL, 'ARGENTINA', 1),
  (143, 'San Isidro', NULL, NULL, 'ARGENTINA', 1),
  (144, 'San Miguel', NULL, NULL, 'ARGENTINA', 1),
  (145, 'San Nicol�s', NULL, NULL, 'ARGENTINA', 1),
  (146, 'San Pedro', NULL, NULL, 'ARGENTINA', 1),
  (147, 'San Vicente', NULL, NULL, 'ARGENTINA', 1),
  (148, 'Suipacha', NULL, NULL, 'ARGENTINA', 1),
  (149, 'Tandil', NULL, NULL, 'ARGENTINA', 1),
  (150, 'Tapalqu�', NULL, NULL, 'ARGENTINA', 1),
  (151, 'Tigre', NULL, NULL, 'ARGENTINA', 1),
  (152, 'Tordillo', NULL, NULL, 'ARGENTINA', 1),
  (153, 'Tornquist', NULL, NULL, 'ARGENTINA', 1),
  (154, 'Trenque Lauquen', NULL, NULL, 'ARGENTINA', 1),
  (155, 'Tres Arroyos', NULL, NULL, 'ARGENTINA', 1),
  (156, 'Tres de Febrero', NULL, NULL, 'ARGENTINA', 1),
  (157, 'Tres Lomas', NULL, NULL, 'ARGENTINA', 1),
  (158, 'Veinticinco de Mayo', NULL, NULL, 'ARGENTINA', 1),
  (159, 'Vicente L�pez', NULL, NULL, 'ARGENTINA', 1),
  (160, 'Villa Gesell', NULL, NULL, 'ARGENTINA', 1),
  (161, 'Villarino', NULL, NULL, 'ARGENTINA', 1),
  (162, 'Z�rate', NULL, NULL, 'ARGENTINA', 1),
  (163, 'Ambato', NULL, NULL, 'ARGENTINA', 2),
  (164, 'Ancasti', NULL, NULL, 'ARGENTINA', 2),
  (165, 'Andalgal�', NULL, NULL, 'ARGENTINA', 2),
  (166, 'Antofagasta de la Sierra', NULL, NULL, 'ARGENTINA', 2),
  (167, 'Bel�n', NULL, NULL, 'ARGENTINA', 2),
  (168, 'Capay�n', NULL, NULL, 'ARGENTINA', 2),
  (169, 'Capital', NULL, NULL, 'ARGENTINA', 2),
  (170, 'El Alto', NULL, NULL, 'ARGENTINA', 2),
  (171, 'Fray Mamerto Esqui�', NULL, NULL, 'ARGENTINA', 2),
  (172, 'La Paz', NULL, NULL, 'ARGENTINA', 2),
  (173, 'Pacl�n', NULL, NULL, 'ARGENTINA', 2),
  (174, 'Pom�n', NULL, NULL, 'ARGENTINA', 2),
  (175, 'Santa Mar�a', NULL, NULL, 'ARGENTINA', 2),
  (176, 'Santa Rosa', NULL, NULL, 'ARGENTINA', 2),
  (177, 'Tinogasta', NULL, NULL, 'ARGENTINA', 2),
  (178, 'Valle Viejo', NULL, NULL, 'ARGENTINA', 2),
  (179, 'Almirante Brown', NULL, NULL, 'ARGENTINA', 3),
  (180, 'Bermejo', NULL, NULL, 'ARGENTINA', 3),
  (181, 'Chacabuco', NULL, NULL, 'ARGENTINA', 3),
  (182, 'Comandante Fern�ndez', NULL, NULL, 'ARGENTINA', 3),
  (183, 'Doce de Octubre', NULL, NULL, 'ARGENTINA', 3),
  (184, 'Dos de Abril', NULL, NULL, 'ARGENTINA', 3),
  (185, 'Fray Justo Santa Mar�a de Oro', NULL, NULL, 'ARGENTINA', 3),
  (186, 'General Belgrano', NULL, NULL, 'ARGENTINA', 3),
  (187, 'General Donovan', NULL, NULL, 'ARGENTINA', 3),
  (188, 'General G�emes', NULL, NULL, 'ARGENTINA', 3),
  (189, 'Independencia', NULL, NULL, 'ARGENTINA', 3),
  (190, 'Libertad', NULL, NULL, 'ARGENTINA', 3),
  (191, 'Libertador General San Mart�n', NULL, NULL, 'ARGENTINA', 3),
  (192, 'Maip�', NULL, NULL, 'ARGENTINA', 3),
  (193, 'Mayor Luis Jorge Fontana', NULL, NULL, 'ARGENTINA', 3),
  (194, 'Nueve de Julio', NULL, NULL, 'ARGENTINA', 3),
  (195, 'O''Higgins', NULL, NULL, 'ARGENTINA', 3),
  (196, 'Presidencia de la Plaza', NULL, NULL, 'ARGENTINA', 3),
  (197, 'Primero de Mayo', NULL, NULL, 'ARGENTINA', 3),
  (198, 'Quitilipi', NULL, NULL, 'ARGENTINA', 3),
  (199, 'San Fernando', NULL, NULL, 'ARGENTINA', 3),
  (200, 'San Lorenzo', NULL, NULL, 'ARGENTINA', 3),
  (201, 'Sargento Cabral', NULL, NULL, 'ARGENTINA', 3),
  (202, 'Tapenag�', NULL, NULL, 'ARGENTINA', 3),
  (203, 'Veinticinco de Mayo', NULL, NULL, 'ARGENTINA', 3),
  (204, 'Biedma', NULL, NULL, 'ARGENTINA', 4),
  (205, 'Cushamen', NULL, NULL, 'ARGENTINA', 4),
  (206, 'Escalante', NULL, NULL, 'ARGENTINA', 4),
  (207, 'Florentino Ameghino', NULL, NULL, 'ARGENTINA', 4),
  (208, 'Futaleuf�', NULL, NULL, 'ARGENTINA', 4),
  (209, 'Gaiman', NULL, NULL, 'ARGENTINA', 4),
  (210, 'Gastre', NULL, NULL, 'ARGENTINA', 4),
  (211, 'Langui�eo', NULL, NULL, 'ARGENTINA', 4),
  (212, 'M�rtires', NULL, NULL, 'ARGENTINA', 4),
  (213, 'Paso de Indios', NULL, NULL, 'ARGENTINA', 4),
  (214, 'Rawson', NULL, NULL, 'ARGENTINA', 4),
  (215, 'R�o Senguer', NULL, NULL, 'ARGENTINA', 4),
  (216, 'Sarmiento', NULL, NULL, 'ARGENTINA', 4),
  (217, 'Tehuelches', NULL, NULL, 'ARGENTINA', 4),
  (218, 'Telsen', NULL, NULL, 'ARGENTINA', 4),
  (219, 'Calamuchita', NULL, NULL, 'ARGENTINA', 5),
  (220, 'Capital', NULL, NULL, 'ARGENTINA', 5),
  (221, 'Col�n', NULL, NULL, 'ARGENTINA', 5),
  (222, 'Cruz del Eje', NULL, NULL, 'ARGENTINA', 5),
  (223, 'General Roca', NULL, NULL, 'ARGENTINA', 5),
  (224, 'General San Mart�n', NULL, NULL, 'ARGENTINA', 5),
  (225, 'Ischil�n', NULL, NULL, 'ARGENTINA', 5),
  (226, 'Ju�rez Celman', NULL, NULL, 'ARGENTINA', 5),
  (227, 'Marcos Ju�rez', NULL, NULL, 'ARGENTINA', 5),
  (228, 'Minas', NULL, NULL, 'ARGENTINA', 5),
  (229, 'Pocho', NULL, NULL, 'ARGENTINA', 5),
  (230, 'Presidente Roque S�enz Pe�a', NULL, NULL, 'ARGENTINA', 5),
  (231, 'Punilla', NULL, NULL, 'ARGENTINA', 5),
  (232, 'R�o Cuarto', NULL, NULL, 'ARGENTINA', 5),
  (233, 'R�o Primero', NULL, NULL, 'ARGENTINA', 5),
  (234, 'R�o Seco', NULL, NULL, 'ARGENTINA', 5),
  (235, 'R�o Segundo', NULL, NULL, 'ARGENTINA', 5),
  (236, 'San Alberto', NULL, NULL, 'ARGENTINA', 5),
  (237, 'San Javier', NULL, NULL, 'ARGENTINA', 5),
  (238, 'San Justo', NULL, NULL, 'ARGENTINA', 5),
  (239, 'Santa Mar�a', NULL, NULL, 'ARGENTINA', 5),
  (240, 'Sobremonte', NULL, NULL, 'ARGENTINA', 5),
  (241, 'Tercero Arriba', NULL, NULL, 'ARGENTINA', 5),
  (242, 'Totoral', NULL, NULL, 'ARGENTINA', 5),
  (243, 'Tulumba', NULL, NULL, 'ARGENTINA', 5),
  (244, 'Uni�n', NULL, NULL, 'ARGENTINA', 5),
  (245, 'Ber�n de Astrada', NULL, NULL, 'ARGENTINA', 6),
  (246, 'Bella Vista', NULL, NULL, 'ARGENTINA', 6),
  (247, 'Capital', NULL, NULL, 'ARGENTINA', 6),
  (248, 'Concepci�n', NULL, NULL, 'ARGENTINA', 6),
  (249, 'Curuz� Cuati�', NULL, NULL, 'ARGENTINA', 6),
  (250, 'Empedrado', NULL, NULL, 'ARGENTINA', 6),
  (251, 'Esquina', NULL, NULL, 'ARGENTINA', 6),
  (252, 'General Alvear', NULL, NULL, 'ARGENTINA', 6),
  (253, 'General Paz', NULL, NULL, 'ARGENTINA', 6),
  (254, 'Goya', NULL, NULL, 'ARGENTINA', 6),
  (255, 'Itat�', NULL, NULL, 'ARGENTINA', 6),
  (256, 'Ituzaing�', NULL, NULL, 'ARGENTINA', 6),
  (257, 'Lavalle', NULL, NULL, 'ARGENTINA', 6),
  (258, 'Mburucuy�', NULL, NULL, 'ARGENTINA', 6),
  (259, 'Mercedes', NULL, NULL, 'ARGENTINA', 6),
  (260, 'Monte Caseros', NULL, NULL, 'ARGENTINA', 6),
  (261, 'Paso de los Libres', NULL, NULL, 'ARGENTINA', 6),
  (262, 'Saladas', NULL, NULL, 'ARGENTINA', 6),
  (263, 'San Cosme', NULL, NULL, 'ARGENTINA', 6),
  (264, 'San Luis del Palmar', NULL, NULL, 'ARGENTINA', 6),
  (265, 'San Mart�n', NULL, NULL, 'ARGENTINA', 6),
  (266, 'San Miguel', NULL, NULL, 'ARGENTINA', 6),
  (267, 'San Roque', NULL, NULL, 'ARGENTINA', 6),
  (268, 'Santo Tom�', NULL, NULL, 'ARGENTINA', 6),
  (269, 'Sauce', NULL, NULL, 'ARGENTINA', 6),
  (270, 'Col�n', NULL, NULL, 'ARGENTINA', 7),
  (271, 'Concordia', NULL, NULL, 'ARGENTINA', 7),
  (272, 'Diamante', NULL, NULL, 'ARGENTINA', 7),
  (273, 'Federaci�n', NULL, NULL, 'ARGENTINA', 7),
  (274, 'Federal', NULL, NULL, 'ARGENTINA', 7),
  (275, 'Feliciano', NULL, NULL, 'ARGENTINA', 7),
  (276, 'Gualeguay', NULL, NULL, 'ARGENTINA', 7),
  (277, 'Gualeguaych�', NULL, NULL, 'ARGENTINA', 7),
  (278, 'Islas del Ibicuy', NULL, NULL, 'ARGENTINA', 7),
  (279, 'La Paz', NULL, NULL, 'ARGENTINA', 7),
  (280, 'Nogoy�', NULL, NULL, 'ARGENTINA', 7),
  (281, 'Paran�', NULL, NULL, 'ARGENTINA', 7),
  (282, 'San Salvador', NULL, NULL, 'ARGENTINA', 7),
  (283, 'Tala', NULL, NULL, 'ARGENTINA', 7),
  (284, 'Uruguay', NULL, NULL, 'ARGENTINA', 7),
  (285, 'Victoria', NULL, NULL, 'ARGENTINA', 7),
  (286, 'Villaguay', NULL, NULL, 'ARGENTINA', 7),
  (287, 'Bermejo', NULL, NULL, 'ARGENTINA', 8),
  (288, 'Formosa', NULL, NULL, 'ARGENTINA', 8),
  (289, 'Laishi', NULL, NULL, 'ARGENTINA', 8),
  (290, 'Matacos', NULL, NULL, 'ARGENTINA', 8),
  (291, 'Pati�o', NULL, NULL, 'ARGENTINA', 8),
  (292, 'Pilag�s', NULL, NULL, 'ARGENTINA', 8),
  (293, 'Pilcomayo', NULL, NULL, 'ARGENTINA', 8),
  (294, 'Piran�', NULL, NULL, 'ARGENTINA', 8),
  (295, 'Ram�n Lista', NULL, NULL, 'ARGENTINA', 8),
  (296, 'Cochinoca', NULL, NULL, 'ARGENTINA', 9),
  (297, 'Doctor Manuel Belgrano', NULL, NULL, 'ARGENTINA', 9),
  (298, 'El Carmen', NULL, NULL, 'ARGENTINA', 9),
  (299, 'Humahuaca', NULL, NULL, 'ARGENTINA', 9),
  (300, 'Ledesma', NULL, NULL, 'ARGENTINA', 9),
  (301, 'Palpal�', NULL, NULL, 'ARGENTINA', 9),
  (302, 'Rinconada', NULL, NULL, 'ARGENTINA', 9),
  (303, 'San Antonio', NULL, NULL, 'ARGENTINA', 9),
  (304, 'San Pedro', NULL, NULL, 'ARGENTINA', 9),
  (305, 'Santa B�rbara', NULL, NULL, 'ARGENTINA', 9),
  (306, 'Santa Catalina', NULL, NULL, 'ARGENTINA', 9),
  (307, 'Susques', NULL, NULL, 'ARGENTINA', 9),
  (308, 'Tilcara', NULL, NULL, 'ARGENTINA', 9),
  (309, 'Tumbaya', NULL, NULL, 'ARGENTINA', 9),
  (310, 'Valle Grande', NULL, NULL, 'ARGENTINA', 9),
  (311, 'Yavi', NULL, NULL, 'ARGENTINA', 9),
  (312, 'Atreuc�', NULL, NULL, 'ARGENTINA', 10),
  (313, 'Caleu Caleu', NULL, NULL, 'ARGENTINA', 10),
  (314, 'Capital', NULL, NULL, 'ARGENTINA', 10),
  (315, 'Catril�', NULL, NULL, 'ARGENTINA', 10),
  (316, 'Chalileo', NULL, NULL, 'ARGENTINA', 10),
  (317, 'Chapaleuf�', NULL, NULL, 'ARGENTINA', 10),
  (318, 'Chical Co', NULL, NULL, 'ARGENTINA', 10),
  (319, 'Conhelo', NULL, NULL, 'ARGENTINA', 10),
  (320, 'Curac�', NULL, NULL, 'ARGENTINA', 10),
  (321, 'Guatrach�', NULL, NULL, 'ARGENTINA', 10),
  (322, 'Hucal', NULL, NULL, 'ARGENTINA', 10),
  (323, 'Lihuel Calel', NULL, NULL, 'ARGENTINA', 10),
  (324, 'Limay Mahuida', NULL, NULL, 'ARGENTINA', 10),
  (325, 'Loventu�', NULL, NULL, 'ARGENTINA', 10),
  (326, 'Marac�', NULL, NULL, 'ARGENTINA', 10),
  (327, 'Puel�n', NULL, NULL, 'ARGENTINA', 10),
  (328, 'Quem� Quem�', NULL, NULL, 'ARGENTINA', 10),
  (329, 'Rancul', NULL, NULL, 'ARGENTINA', 10),
  (330, 'Realic�', NULL, NULL, 'ARGENTINA', 10),
  (331, 'Toay', NULL, NULL, 'ARGENTINA', 10),
  (332, 'Trenel', NULL, NULL, 'ARGENTINA', 10),
  (333, 'Utrac�n', NULL, NULL, 'ARGENTINA', 10),
  (334, 'Arauco', NULL, NULL, 'ARGENTINA', 11),
  (335, 'Capital', NULL, NULL, 'ARGENTINA', 11),
  (336, 'Castro Barros', NULL, NULL, 'ARGENTINA', 11),
  (337, 'Chamical', NULL, NULL, 'ARGENTINA', 11),
  (338, 'Chilecito', NULL, NULL, 'ARGENTINA', 11),
  (339, 'Coronel Felipe Varela', NULL, NULL, 'ARGENTINA', 11),
  (340, 'Famatina', NULL, NULL, 'ARGENTINA', 11),
  (341, 'General �ngel V. Pe�aloza', NULL, NULL, 'ARGENTINA', 11),
  (342, 'General Belgrano', NULL, NULL, 'ARGENTINA', 11),
  (343, 'General Juan Facundo Quiroga', NULL, NULL, 'ARGENTINA', 11),
  (344, 'General Lamadrid', NULL, NULL, 'ARGENTINA', 11),
  (345, 'General Ocampo', NULL, NULL, 'ARGENTINA', 11),
  (346, 'General San Mart�n', NULL, NULL, 'ARGENTINA', 11),
  (347, 'Independencia', NULL, NULL, 'ARGENTINA', 11),
  (348, 'Rosario Vera Pe�aloza', NULL, NULL, 'ARGENTINA', 11),
  (349, 'Sanagasta', NULL, NULL, 'ARGENTINA', 11),
  (350, 'San Blas de los Sauces', NULL, NULL, 'ARGENTINA', 11),
  (351, 'Vinchina', NULL, NULL, 'ARGENTINA', 11),
  (352, 'Capital', NULL, NULL, 'ARGENTINA', 12),
  (353, 'General Alvear', NULL, NULL, 'ARGENTINA', 12),
  (354, 'Godoy Cruz', NULL, NULL, 'ARGENTINA', 12),
  (355, 'Guaymall�n', NULL, NULL, 'ARGENTINA', 12),
  (356, 'Jun�n', NULL, NULL, 'ARGENTINA', 12),
  (357, 'La Paz', NULL, NULL, 'ARGENTINA', 12),
  (358, 'Las Heras', NULL, NULL, 'ARGENTINA', 12),
  (359, 'Lavalle', NULL, NULL, 'ARGENTINA', 12),
  (360, 'Luj�n de Cuyo', NULL, NULL, 'ARGENTINA', 12),
  (361, 'Maip�', NULL, NULL, 'ARGENTINA', 12),
  (362, 'Malarg�e', NULL, NULL, 'ARGENTINA', 12),
  (363, 'Rivadavia', NULL, NULL, 'ARGENTINA', 12),
  (364, 'San Carlos', NULL, NULL, 'ARGENTINA', 12),
  (365, 'San Mart�n', NULL, NULL, 'ARGENTINA', 12),
  (366, 'San Rafael', NULL, NULL, 'ARGENTINA', 12),
  (367, 'Santa Rosa', NULL, NULL, 'ARGENTINA', 12),
  (368, 'Tunuy�n', NULL, NULL, 'ARGENTINA', 12),
  (369, 'Tupungato', NULL, NULL, 'ARGENTINA', 12),
  (370, 'Ap�stoles', NULL, NULL, 'ARGENTINA', 13),
  (371, 'Caingu�s', NULL, NULL, 'ARGENTINA', 13),
  (372, 'Candelaria', NULL, NULL, 'ARGENTINA', 13),
  (373, 'Capital', NULL, NULL, 'ARGENTINA', 13),
  (374, 'Concepci�n', NULL, NULL, 'ARGENTINA', 13),
  (375, 'Eldorado', NULL, NULL, 'ARGENTINA', 13),
  (376, 'General Manuel Belgrano', NULL, NULL, 'ARGENTINA', 13),
  (377, 'Guaran�', NULL, NULL, 'ARGENTINA', 13),
  (378, 'Iguaz�', NULL, NULL, 'ARGENTINA', 13),
  (379, 'Leandro N. Alem', NULL, NULL, 'ARGENTINA', 13),
  (380, 'Libertador General San Mart�n', NULL, NULL, 'ARGENTINA', 13),
  (381, 'Montecarlo', NULL, NULL, 'ARGENTINA', 13),
  (382, 'Ober�', NULL, NULL, 'ARGENTINA', 13),
  (383, 'San Ignacio', NULL, NULL, 'ARGENTINA', 13),
  (384, 'San Javier', NULL, NULL, 'ARGENTINA', 13),
  (385, 'San Pedro', NULL, NULL, 'ARGENTINA', 13),
  (386, 'Veinticinco de Mayo', NULL, NULL, 'ARGENTINA', 13),
  (387, 'Alumin�', NULL, NULL, 'ARGENTINA', 14),
  (388, 'A�elo', NULL, NULL, 'ARGENTINA', 14),
  (389, 'Cat�n Lil', NULL, NULL, 'ARGENTINA', 14),
  (390, 'Chos Malal', NULL, NULL, 'ARGENTINA', 14),
  (391, 'Coll�n Cur�', NULL, NULL, 'ARGENTINA', 14),
  (392, 'Confluencia', NULL, NULL, 'ARGENTINA', 14),
  (393, 'Huiliches', NULL, NULL, 'ARGENTINA', 14),
  (394, 'L�car', NULL, NULL, 'ARGENTINA', 14),
  (395, 'Loncopu�', NULL, NULL, 'ARGENTINA', 14),
  (396, 'Los Lagos', NULL, NULL, 'ARGENTINA', 14),
  (397, 'Minas', NULL, NULL, 'ARGENTINA', 14),
  (398, 'Pehuenches', NULL, NULL, 'ARGENTINA', 14),
  (399, 'Picunches', NULL, NULL, 'ARGENTINA', 14),
  (400, 'Pic�n Leuf�', NULL, NULL, 'ARGENTINA', 14),
  (401, 'Zapala', NULL, NULL, 'ARGENTINA', 14),
  (402, '�orqu�n', NULL, NULL, 'ARGENTINA', 14),
  (403, 'Adolfo Alsina', NULL, NULL, 'ARGENTINA', 15),
  (404, 'Avellaneda', NULL, NULL, 'ARGENTINA', 15),
  (405, 'Bariloche', NULL, NULL, 'ARGENTINA', 15),
  (406, 'Conesa', NULL, NULL, 'ARGENTINA', 15),
  (407, 'El Cuy', NULL, NULL, 'ARGENTINA', 15),
  (408, 'General Roca', NULL, NULL, 'ARGENTINA', 15),
  (409, 'Nueve de Julio', NULL, NULL, 'ARGENTINA', 15),
  (410, 'Pichi Mahuida', NULL, NULL, 'ARGENTINA', 15),
  (411, 'Pilcaniyeu', NULL, NULL, 'ARGENTINA', 15),
  (412, 'San Antonio', NULL, NULL, 'ARGENTINA', 15),
  (413, 'Valcheta', NULL, NULL, 'ARGENTINA', 15),
  (414, 'Veinticinco de Mayo', NULL, NULL, 'ARGENTINA', 15),
  (415, '�orquinc�', NULL, NULL, 'ARGENTINA', 15),
  (416, 'Anta', NULL, NULL, 'ARGENTINA', 16),
  (417, 'Cachi', NULL, NULL, 'ARGENTINA', 16),
  (418, 'Cafayate', NULL, NULL, 'ARGENTINA', 16),
  (419, 'Capital', NULL, NULL, 'ARGENTINA', 16),
  (420, 'Cerrillos', NULL, NULL, 'ARGENTINA', 16),
  (421, 'Chicoana', NULL, NULL, 'ARGENTINA', 16),
  (422, 'General G�emes', NULL, NULL, 'ARGENTINA', 16),
  (423, 'General Jos� de San Mart�n', NULL, NULL, 'ARGENTINA', 16),
  (424, 'Guachipas', NULL, NULL, 'ARGENTINA', 16),
  (425, 'Iruya', NULL, NULL, 'ARGENTINA', 16),
  (426, 'La Caldera', NULL, NULL, 'ARGENTINA', 16),
  (427, 'La Candelaria', NULL, NULL, 'ARGENTINA', 16),
  (428, 'La Poma', NULL, NULL, 'ARGENTINA', 16),
  (429, 'La Vi�a', NULL, NULL, 'ARGENTINA', 16),
  (430, 'Los Andes', NULL, NULL, 'ARGENTINA', 16),
  (431, 'Met�n', NULL, NULL, 'ARGENTINA', 16),
  (432, 'Molinos', NULL, NULL, 'ARGENTINA', 16),
  (433, 'Or�n', NULL, NULL, 'ARGENTINA', 16),
  (434, 'Rivadavia', NULL, NULL, 'ARGENTINA', 16),
  (435, 'Rosario de la Frontera', NULL, NULL, 'ARGENTINA', 16),
  (436, 'Rosario de Lerma', NULL, NULL, 'ARGENTINA', 16),
  (437, 'San Carlos', NULL, NULL, 'ARGENTINA', 16),
  (438, 'Santa Victoria', NULL, NULL, 'ARGENTINA', 16),
  (439, 'Albard�n', NULL, NULL, 'ARGENTINA', 17),
  (440, 'Angaco', NULL, NULL, 'ARGENTINA', 17),
  (441, 'Calingasta', NULL, NULL, 'ARGENTINA', 17),
  (442, 'Capital', NULL, NULL, 'ARGENTINA', 17),
  (443, 'Caucete', NULL, NULL, 'ARGENTINA', 17),
  (444, 'Chimbas', NULL, NULL, 'ARGENTINA', 17),
  (445, 'Iglesia', NULL, NULL, 'ARGENTINA', 17),
  (446, 'J�chal', NULL, NULL, 'ARGENTINA', 17),
  (447, 'Nueve de Julio', NULL, NULL, 'ARGENTINA', 17),
  (448, 'Pocito', NULL, NULL, 'ARGENTINA', 17),
  (449, 'Rawson', NULL, NULL, 'ARGENTINA', 17),
  (450, 'Rivadavia', NULL, NULL, 'ARGENTINA', 17),
  (451, 'San Mart�n', NULL, NULL, 'ARGENTINA', 17),
  (452, 'Santa Luc�a', NULL, NULL, 'ARGENTINA', 17),
  (453, 'Sarmiento', NULL, NULL, 'ARGENTINA', 17),
  (454, 'Ullum', NULL, NULL, 'ARGENTINA', 17),
  (455, 'Valle F�rtil', NULL, NULL, 'ARGENTINA', 17),
  (456, 'Veinticinco de Mayo', NULL, NULL, 'ARGENTINA', 17),
  (457, 'Zonda', NULL, NULL, 'ARGENTINA', 17),
  (458, 'Ayacucho', NULL, NULL, 'ARGENTINA', 18),
  (459, 'Belgrano', NULL, NULL, 'ARGENTINA', 18),
  (460, 'Chacabuco', NULL, NULL, 'ARGENTINA', 18),
  (461, 'Coronel Pringles', NULL, NULL, 'ARGENTINA', 18),
  (462, 'General Pedernera', NULL, NULL, 'ARGENTINA', 18),
  (463, 'Gobernador Dupuy', NULL, NULL, 'ARGENTINA', 18),
  (464, 'Jun�n', NULL, NULL, 'ARGENTINA', 18),
  (465, 'La Capital', NULL, NULL, 'ARGENTINA', 18),
  (466, 'Libertador General San Mart�n', NULL, NULL, 'ARGENTINA', 18),
  (467, 'Corpen Aike', NULL, NULL, 'ARGENTINA', 19),
  (468, 'Deseado', NULL, NULL, 'ARGENTINA', 19),
  (469, 'G�er Aike', NULL, NULL, 'ARGENTINA', 19),
  (470, 'Lago Argentino', NULL, NULL, 'ARGENTINA', 19),
  (471, 'Lago Buenos Aires', NULL, NULL, 'ARGENTINA', 19),
  (472, 'Magallanes', NULL, NULL, 'ARGENTINA', 19),
  (473, 'R�o Chico', NULL, NULL, 'ARGENTINA', 19),
  (474, 'Caseros', NULL, NULL, 'ARGENTINA', 18),
  (475, 'Castellanos', NULL, NULL, 'ARGENTINA', 18),
  (476, 'Constituci�n', NULL, NULL, 'ARGENTINA', 18),
  (477, 'Garay', NULL, NULL, 'ARGENTINA', 18),
  (478, 'General L�pez', NULL, NULL, 'ARGENTINA', 18),
  (479, 'General Obligado', NULL, NULL, 'ARGENTINA', 18),
  (480, 'Iriondo', NULL, NULL, 'ARGENTINA', 18),
  (481, 'Las Colonias', NULL, NULL, 'ARGENTINA', 18),
  (482, 'Nueve de Julio', NULL, NULL, 'ARGENTINA', 18),
  (483, 'Rosario', NULL, NULL, 'ARGENTINA', 18),
  (484, 'San Crist�bal', NULL, NULL, 'ARGENTINA', 18),
  (485, 'San Javier', NULL, NULL, 'ARGENTINA', 18),
  (486, 'San Jer�nimo', NULL, NULL, 'ARGENTINA', 18),
  (487, 'San Justo', NULL, NULL, 'ARGENTINA', 18),
  (488, 'San Lorenzo', NULL, NULL, 'ARGENTINA', 18),
  (489, 'San Mart�n', NULL, NULL, 'ARGENTINA', 18),
  (490, 'Vera', NULL, NULL, 'ARGENTINA', 18),
  (491, 'Aguirre', NULL, NULL, 'ARGENTINA', 21),
  (492, 'Alberdi', NULL, NULL, 'ARGENTINA', 21),
  (493, 'Atamisqui', NULL, NULL, 'ARGENTINA', 21),
  (494, 'Avellaneda', NULL, NULL, 'ARGENTINA', 21),
  (495, 'Banda', NULL, NULL, 'ARGENTINA', 21),
  (496, 'Belgrano', NULL, NULL, 'ARGENTINA', 21),
  (497, 'Capital', NULL, NULL, 'ARGENTINA', 21),
  (498, 'Choya', NULL, NULL, 'ARGENTINA', 21),
  (499, 'Copo', NULL, NULL, 'ARGENTINA', 21),
  (500, 'Figueroa', NULL, NULL, 'ARGENTINA', 21);
INSERT INTO tb_estado (id, nome, sigla, codigo_ibge, pais, provincia) VALUES
  (501, 'General Taboada', NULL, NULL, 'ARGENTINA', 21),
  (502, 'Guasay�n', NULL, NULL, 'ARGENTINA', 21),
  (503, 'Jim�nez', NULL, NULL, 'ARGENTINA', 21),
  (504, 'Juan F. Ibarra', NULL, NULL, 'ARGENTINA', 21),
  (505, 'Loreto', NULL, NULL, 'ARGENTINA', 21),
  (506, 'Mitre', NULL, NULL, 'ARGENTINA', 21),
  (507, 'Moreno', NULL, NULL, 'ARGENTINA', 21),
  (508, 'Ojo de Agua', NULL, NULL, 'ARGENTINA', 21),
  (509, 'Pellegrini', NULL, NULL, 'ARGENTINA', 21),
  (510, 'Quebrachos', NULL, NULL, 'ARGENTINA', 21),
  (511, 'R�o Hondo', NULL, NULL, 'ARGENTINA', 21),
  (512, 'Rivadavia', NULL, NULL, 'ARGENTINA', 21),
  (513, 'Robles', NULL, NULL, 'ARGENTINA', 21),
  (514, 'Salavina', NULL, NULL, 'ARGENTINA', 21),
  (515, 'San Mart�n', NULL, NULL, 'ARGENTINA', 21),
  (516, 'Sarmiento', NULL, NULL, 'ARGENTINA', 21),
  (517, 'Sil�pica', NULL, NULL, 'ARGENTINA', 21),
  (518, 'R�o Grande', NULL, NULL, 'ARGENTINA', 22),
  (519, 'Ushuaia', NULL, NULL, 'ARGENTINA', 22),
  (520, 'Burruyac�', NULL, NULL, 'ARGENTINA', 23),
  (521, 'Capital', NULL, NULL, 'ARGENTINA', 23),
  (522, 'Chicligasta', NULL, NULL, 'ARGENTINA', 23),
  (523, 'Cruz Alta', NULL, NULL, 'ARGENTINA', 23),
  (524, 'Famaill�', NULL, NULL, 'ARGENTINA', 23),
  (525, 'Graneros', NULL, NULL, 'ARGENTINA', 23),
  (526, 'Juan Bautista Alberdi', NULL, NULL, 'ARGENTINA', 23),
  (527, 'La Cocha', NULL, NULL, 'ARGENTINA', 23),
  (528, 'Leales', NULL, NULL, 'ARGENTINA', 23),
  (529, 'Lules', NULL, NULL, 'ARGENTINA', 23),
  (530, 'Monteros', NULL, NULL, 'ARGENTINA', 23),
  (531, 'R�o Chico', NULL, NULL, 'ARGENTINA', 23),
  (532, 'Simoca', NULL, NULL, 'ARGENTINA', 23),
  (533, 'Taf� del Valle', NULL, NULL, 'ARGENTINA', 23),
  (534, 'Taf� Viejo', NULL, NULL, 'ARGENTINA', 23),
  (535, 'Trancas', NULL, NULL, 'ARGENTINA', 23),
  (536, 'Yerba Buena', NULL, NULL, 'ARGENTINA', 23),
  (537, 'Asunci�n', NULL, NULL, 'PARAGUAI', NULL),
  (538, 'Concepci�n', NULL, NULL, 'PARAGUAI', NULL),
  (539, 'San Pedro', NULL, NULL, 'PARAGUAI', NULL),
  (540, 'Cordillera', NULL, NULL, 'PARAGUAI', NULL),
  (541, 'Guair�', NULL, NULL, 'PARAGUAI', NULL),
  (542, 'Caaguaz�', NULL, NULL, 'PARAGUAI', NULL),
  (543, 'Caazap�', NULL, NULL, 'PARAGUAI', NULL),
  (544, 'Itap�a', NULL, NULL, 'PARAGUAI', NULL),
  (545, 'Misiones', NULL, NULL, 'PARAGUAI', NULL),
  (546, 'Paraguar�', NULL, NULL, 'PARAGUAI', NULL),
  (547, 'Alto Paran�', NULL, NULL, 'PARAGUAI', NULL),
  (548, 'Central', NULL, NULL, 'PARAGUAI', NULL),
  (549, '�eembuc�', NULL, NULL, 'PARAGUAI', NULL),
  (550, 'Amambay', NULL, NULL, 'PARAGUAI', NULL),
  (551, 'Canindey�', NULL, NULL, 'PARAGUAI', NULL),
  (552, 'Presidente Hayes', NULL, NULL, 'PARAGUAI', NULL),
  (553, 'Boquer�n', NULL, NULL, 'PARAGUAI', NULL),
  (554, 'Alto Paraguay', NULL, NULL, 'PARAGUAI', NULL);
