INSERT INTO tb_provincia (id, descricao, pais) VALUES
  (1, 'Buenos Aires', 'ARGENTINA'),
  (2, 'Catamarca', 'ARGENTINA'),
  (3, 'Chaco', 'ARGENTINA'),
  (4, 'Chubut', 'ARGENTINA'),
  (5, 'C�rdoba', 'ARGENTINA'),
  (6, 'Corrientes', 'ARGENTINA'),
  (7, 'Entre R�os', 'ARGENTINA'),
  (8, 'Formosa', 'ARGENTINA'),
  (9, 'Jujuy', 'ARGENTINA'),
  (10, 'La Pampa', 'ARGENTINA'),
  (11, 'La Rioja', 'ARGENTINA'),
  (12, 'Mendoza', 'ARGENTINA'),
  (13, 'Misiones', 'ARGENTINA'),
  (14, 'Neuqu�n', 'ARGENTINA'),
  (15, 'R�o Negro', 'ARGENTINA'),
  (16, 'Salta', 'ARGENTINA'),
  (17, 'San Juan', 'ARGENTINA'),
  (18, 'San Luis', 'ARGENTINA'),
  (19, 'Santa Cruz', 'ARGENTINA'),
  (20, 'Santa Fe', 'ARGENTINA'),
  (21, 'Santiago del Estero', 'ARGENTINA'),
  (22, 'Tierra del Fuego', 'ARGENTINA'),
  (23, 'Tucum�n', 'ARGENTINA');
